### ISSUE TITLE
Handling "errors" like NXDOMAIN - cache for network, or everything?

### ISSUE THREAD

**Issue by wkumari** [wkumari/draft-vandergaast-edns-client-subnet#1]
Currently the document says:
"In the cache, any resource record in the answer section will be tied to the network specified by the FAMILY, ADDRESS and SCOPE PREFIX-LENGTH fields, as detailed below. Note that the additional and authority sections from a DNS response message are specifically excluded here. Any information cached from these sections MUST NOT be tied to a network. This means that edns-client-subnet option cannot be used to tell some clients that a name exists and others that the name does not exist (NXDOMAIN)."

Is this "right"? If I tell a client at 192.0.2.0 that the A for example.com is 10.10.10.10, can I then (legitimately!) tell another client that example.com doesn't exist? What if there is SERVFAIL; should that invalidate all of the cached entries?

**Comment by wkumari** [comment]
Sent in email:
I don't really know what the right answer here is - if I've claimed that the best address for 192.0.2.0/24 is 10.10.10.10, can I now claim that the name doesn't exist for users at 172.16.5.2?! Or, can I return 10.10.10.10 to uses at 192.0.2.0/24 and then return SERVFAIL for other folk? Both feel wrong - perhaps we need to say that any error (defined later :-P) applies to all entries?!

**Comment by vttale** [comment]
Negative answers should be cached just the same as positive answers.  One salient use case is when the authority knows that there is not good service for IPv6 to a particular area, so it wants to be able to answer noerror/nodata to an AAAA request for a name for which it will answer with v4.  (Yes, there are other implications there w.r.t. v6-only clients, but we do have operational experience in being able to sort some of that out.)

 Another use case is no different than "split horizon" DNS, a feature in several servers, where the look of a zone on one side can be very different w.r.t.  nxdomain/nxrrset than it is on the other side.

This is no different than the power authoritative servers currently have with regard to answering based on resolver address.  Using client address as the key in place of the resolver address should not change what the authority can express with regard to the address.

**Comment by pdevries-quotient** [comment]
There is at least other cases where you would claim NXDOMAIN for one address while responding with an answer for another.   You can do this now with RPZ and client-ip.

**Comment by wkumari** [comment]
Closing OBE events to clean up my Issues dashboard.
