### ISSUE TITLE
examples for strategies for an auth server to choose an answer when it got a short source prefix

### ISSUE THREAD

**Issue by vttale** [wkumari/draft-vandergaast-edns-client-subnet#3]
"   The specific logic that an Authoritative Nameserver uses to choose a
   tailored response is not in the scope of this document.  Implementers
   are encouraged, however, to consider carefully their selection of
   SCOPE PREFIX-LENGTH for the response in the event that the best
   tailored response cannot be determined.  "

It'd probably be good to give some examples for "consider carefully".

**Comment by wkumari** [comment]
Closing OBE events to clean up my Issues dashboard.
