### ISSUE TITLE
Forwarders and cacheability vs privacy

### ISSUE THREAD

**Issue by vttale** [wkumari/draft-vandergaast-edns-client-subnet#4]
If a Forwarder handles a query where its client requested a specific SOURCE PREFIX-LENGTH, but policy determines that the Recursive Resolver it contacts will not be able to use the ADDRESS provided to it in an ECS option, the Forwarder must send an option with a zero FAMILY and no ADDRESS, and only SOURCE PREFIX-LENGTH set (and SCOPE PREFIX-LENGTH can essentially be any thing, since the Recursive Resolver will use its own value).

The problem arises in that the Recursive Resolver can't send FAMILY and ADDRESS information back down to its client without running afoul of the current Security section that demands the FAMILY and initial SOURCE PREFIX-LENGTH bit of ADDRESS in the response must match those provided in the query.

**Comment by wkumari** [comment]
Closing OBE events to clean up my Issues dashboard.
