### ISSUE TITLE
REFUSED is a poor method for signaling

### ISSUE THREAD

**Issue by vttale** [wkumari/draft-vandergaast-edns-client-subnet#6]
Using REFUSED to signal lack of support for forwarding an address specified in an incoming ECS option is problematic for a couple of reasons.   It is ambiguous as to what aspect of the request was refused; since REFUSED is now commonly used to indicate a lame delegation, it adds another RTT now to distinguish a retryable-REFUSED from an end-of-the-line-REFUSED.

Also, one resolver vendor is opposed to the REFUSED in that it adds an RTT for something that it can just be getting an answer for.  That is, if a client sending the option gets REFUSED, they should be retrying without the address information so that server will use their socket address.  But the server could just go ahead and use that socket address when handling the original query.  (Except, of course, for the problem I raised in Issue #4, about being able to reply with the address that was used.)

The first issue about indicating why it was refused could possibly be addressed by using an EDNS0 extended rcode, but I don't know how dnsop will feel about using an rcode for an option-specific message.  This could also be addressed through versioning with the first octet of the option data (that is, what is currently the first octet of FAMILY).  With versioning we could even address the issue of being able to service the query instead of refusing it.

**Comment by wkumari** [comment]
Closing OBE events to clean up my Issues dashboard.
